server:
  port: 9090

#spring:
#  application:
#    name: GATEWAY-SERVICE
#  datasource:
#    url: jdbc:mysql://localhost:3306/Gateway_db
#    username: root
#    password: lalith
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql

spring:
  application:
    name: GATEWAY-SERVICE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:Gateway_db} #?useSSL=false
    username: ${DB_USERNAME:deepesh}
    password: ${DB_PASSWORD:deepesh}
    hikari:
#      minimumIdle: 2
#      maximumPoolSize: 10
#      idleTimeout: 120000
#      connectionTimeout: 300000
#      leakDetectionThreshold: 300000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:9000/eureka
#    instance:
#      hostname: localhost