server:
  port: 9100

spring:
  application:
    name: SECURITY-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/Security_db
    username: root
    password: lalith
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:9000/eureka
#    instance:
#      hostname: localhost