apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-depl
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 2
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    name: gateway-depl
spec:
  selector:
    app: gateway
  ports:
    - nodePort: 30170
      port: 9200
      targetPort: 9200
      protocol: TCP
  type: NodePort