apiVersion: v1
kind: Service
metadata:
  name: security-app-svc
  labels:
    name: security-app
spec:
  ports:
    - nodePort: 30164
      port: 9100
      targetPort: 9100
      protocol: TCP
  selector:
    app: security-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-app-depl
spec:
  selector:
    matchLabels:
      app: security-app
  replicas: 3
  template:
    metadata:
      labels:
        app: security-app
    spec:
      containers:
        - name: security-app
          image: security-app:1.0
          ports:
            - containerPort: 9100
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf-security  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf-security
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
        