apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  namespace: default
  labels:
    name: gateway
spec:
  ports:
    - nodePort: 30163
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: gateway
  type: NodePort