apiVersion: v1
kind: Service
metadata:
  name: cdms-frontend-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: cdms-frontend
  ports:
    - nodePort: 30170
      port: 3000
      targetPort: 3000
