apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdms-frontend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdms-frontend
  template:
    metadata:
      labels:
        app: cdms-frontend
    spec:
      containers:
        - name: cdms-frontend
          image: lalithkrg/cdms-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: cdms-frontend-svc
spec:
  type: NodePort
  selector:
    app: cdms-frontend
  ports:
    - nodePort: 30170
      port: 3000
      targetPort: 3000
