apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdms-frontend-depl
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdms-frontend
  template:
    metadata:
      labels:
        app: cdms-frontend
    spec:
      containers:
        - name: cdms-frontend
          image: deepesh007/cdms-frontend