apiVersion: v1
kind: Service
metadata:
  name: student-app-svc
  labels:
    name: student-app
spec:
  ports:
    - nodePort: 30165
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: student-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-app-depl
spec:
  selector:
    matchLabels:
      app: student-app
  replicas: 3
  template:
    metadata:
      labels:
        app: student-app
    spec:
      containers:
        - name: student-app
          image: lalithkrg/student-app
          ports:
            - containerPort: 9200
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf-student  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-conf-student
                  key: name
            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials # Secret Name
                  key: username
            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
