apiVersion: v1
kind: Service
metadata:
  name: student-app-svc
  namespace: default
  labels:
    name: student-app
spec:
  ports:
    - nodePort: 30165
      port: 9200
      targetPort: 9200
      protocol: TCP
  selector:
    app: student-app
  type: NodePort